name: Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: sudo docker build --build-arg REDIS_HOST=${{secrets.REDIS_HOST}} --build-arg REDIS_PORT=${{secrets.REDIS_PORT}} --build-arg DATASOURCE_URL=${{secrets.DATASOURCE_URL}} --build-arg DATASOURCE_USER=${{secrets.DATASOURCE_USER}} --build-arg DATASOURCE_PASSWORD=${{secrets.DATASOURCE_PASSWORD}} -t ras-image .

      - name: Stop Docker Containers
        run: sudo docker stop ras-app || true

      - name: Remove Existing Docker Containers
        run: sudo docker rm ras-app || true

      - name: Run Docker Container
        run: sudo docker run --network=host --rm -d -p 8080:8080 -e REDIS_HOST=${{secrets.REDIS_HOST}} -e REDIS_PORT=${{secrets.REDIS_PORT}} -e DATASOURCE_URL=${{secrets.DATASOURCE_URL}} -e DATASOURCE_USER=${{secrets.DATASOURCE_USER}} -e DATASOURCE_PASSWORD=${{secrets.DATASOURCE_PASSWORD}} --name ras-app ras-image
